dat <- read.delim("data/IDH1_MAFs.txt", as.is=TRUE)
dat$labels <- paste(dat$Tumor.sample, dat$X)
dat$Exome.seq <- gsub("%", "", dat$Exome.seq)
dat$Exome.seq <- as.numeric(dat$Exome.seq)
dat$RNA.seq <- gsub("%", "", dat$RNA.seq)
dat$RNA.seq <- as.numeric(dat$RNA.seq)
pdf("paperplots/IDH1_MAFs.pdf")
xx <- barplot(dat$Exome.seq, names.arg=dat$labels, ylim=c(0,100), las=2)
abline(h=50, lty=2)
idx.RNA <-which(!(is.na(dat$RNA.seq)))
points(xx[idx.RNA], dat$RNA.seq[idx.RNA], pch=17)
dev.off()